### PR TITLE
no conditional assign

### PR DESCRIPTION
**Pull request by falentio**

### CODE REVIEW

**Review by fzn0x — APPROVED** [review]

**Comment by falentio** [comment]
may I get hacktoberfest-accepted label sir

**Comment by fzn0x** [comment]
> may I get hacktoberfest-accepted label

Sure :) why not

**Comment by falentio** [comment]
> Sure :) why not

thank you sir 😄

**Comment by fzn0x** [comment]
:D

**Comment by fzn0x** [comment]
> > Sure :) why not
> 
> thank you sir 😄

You are welcome 😄

**Pull request merged**
