### PR TITLE
fix: flickering dark mode theme, closes #118

### LINKED ISSUE #118: Fix flickering dark mode
Is it possible to use only the dark version?
Or to reverse the default theme (dark instead of light) to avoid the little flash at the beginning of the page loading?

### PR DESCRIPTION
**Pull request by fzn0x**
Fix flickering dark mode.
This is not a typical solution for me but it's works.

Please using squash for merge.

Closes #118

### CODE REVIEW

**Comment by fzn0x** [comment]
Address https://github.com/zuramai/mazer/commit/dca4a8a1b2b4076aba9cd15a4b1542bd6b28c1da to fix intermittent issue on laravel mix. The intermitten issue is mix cannot copy the simple-datatable when the simple-datatable is runs first.

**Comment by fzn0x** [comment]
Kindly review and release a new version I think the bug is nowhere to be found now.

**Comment by fzn0x** [comment]
Kindly review, I think the bug is nowhere to be found now. @zuramai 

And can we release it to new version `2.0.2` ?

**Comment by fzn0x** [comment]
Forward from @zuramai on telegram, refactor `<script>` tag inside `<head>` tag

**Comment by zuramai** [comment]
Great PR!

**Pull request merged**
