### PR TITLE
fixed Some of the texts on the dashboard are out of elements

### PR DESCRIPTION
**Pull request by Salisyal**
hello, I have fixed the problem in the template, you can check my pull request to see it

### CODE REVIEW

**Review by zuramai — CHANGES_REQUESTED** [review]
Hi, to make a changes, make sure you run the development mode with `npm run watch`, and the working directory is in `src`

Read more [CONTRIBUTING.md](https://github.com/zuramai/mazer/blob/main/CONTRIBUTING.md)

**Comment by Salisyal** [comment]
hello regarding that i'm not using nodejs or npm can you take a look at the fix i fixed , hope you like it thanks

**Comment by bl0cknumber** [comment]
Make sure to follow [CONTRIBUTING.md](https://github.com/zuramai/mazer/blob/main/CONTRIBUTING.md) before open up a PR

**Comment by bl0cknumber** [comment]
You can ask to reopen and fix the whole step or create a new PR. Thanks

**Pull request closed without merging**
