### PR TITLE
Use !default for all scss variables

### PR DESCRIPTION
**Pull request by Niksac**
In my project, I import Mazer via npm (directly from git, not as npm registry package).

In my main scss file, I do something like this:
```
@import "~mazer/src/assets/scss/app";
```

In my main JS file I do something like this:
```
window.PerfectScrollbar = require('perfect-scrollbar/dist/perfect-scrollbar.min.js');
require('mazer/src/assets/js/mazer.js');
```

This works pretty well and enables me to use all Mazer components (JS stuff needs extra work obviously).

My issue is, that it's hard to customize Mazer styles when importing this way.
The Mazer app.scss imports the variables scss file and immediately "consumes" the variables afterwards.

I solve this by importing the variables file first, then overwrite some of them, and then individually import all other Mazer scss files.

As Mazer is marketet as a theme / template, I suggest defining all variables with the `!default` keyword to enable overwrites.
What do think?

### CODE REVIEW

**Comment by zuramai** [comment]
If the SCSS variables in `_variables.scss` are using `!default`, then it wouldn't override the bootstrap's variables. As a result, it will break many things in the style.

**Comment by Niksac** [comment]
Hi Ahmad,

so sorry I didnt test this change with you build system.
The way things are loaded in there, things will indeed break.

SCSS variables `!default` will only be set If they have not been set before.
So if we load the mazer `_variables.scss` first in the build process, things check out nicely.

The problem is:
The way it's done in the repo, the bootstrap scss is going through its own build process so we can't share variables there.
More precisely I think webpack translates the SCSS variables into CSS variables which work completely different and allows for "later overwrites".


I imported the bootstrap scss in the app.scss file like shown below.
This works, but I don't really like the solution.

```
// 0. Mixins
@import "./mixins/navbar";

// 1. Variables
@import "./variables";

// Import bootstrap
@import "./bootstrap.scss";

// 2. Bootstrap Components Override

// - 2.1. Alert
@import "./components/alert";

```
 
 I will think about a way to change the build system which works for everyone.

**Comment by Niksac** [comment]
Hi Ahmad

If you want, you can have a look and maybe checkout
https://github.com/Niksac/mazer/tree/build-system-updates

In there, I restructured the build system a bit.
A lot of "vendor" files are being required in the package.json but are also part of the repo as static files which make updates harder and also make the theme more difficult to integrate imho.

I rearranged the main scss entry point a bit to also load bootstrap, icon and font requirements from the node modules folder (no more google font dependancy).
If done this way, the variable `default!` stuff works too.

Also I took the "toastify" page as an example and loaded the JS and CSS dependencies from the (already installed) npm version.
The static "vendor" version has been removed.
This could be done for the other JS dependancies as well.

Maybe you can check the branch out, run a build and take a look.

Nik

**Comment by zuramai** [comment]
Hello, sorry for late reply. I have checked out your [build-system-updates](https://github.com/Niksac/mazer/tree/build-system-updates) branch and it's great! Could you make a pull request out of it?

And I also planned to migrate from **laravel-mix** to **vite**. There are a bunch of useful vite plugins such as [vite-plugin-nunjucks](https://github.com/Jax-p/vite-plugin-nunjucks). Vite is much faster and efficient than laravel-mix. What do you think about this?

**Comment by Niksac** [comment]
Hi @zuramai 

OK, I will try to load the remaning components from its npm packages and when it's all done, I'll do a pull request.

Regarding vite: Unfortunately I don't know vite so I can't give a qualified opinion.
The mix config for mazer does not contain much customization so I guess it would be easy to migrate this to an alternative.
As vite does not bundle in local development it should indeed be a much faster experience there.

**Comment by Niksac** [comment]
Another thought:
The dist folder which contains bundling results should probably be excluded from the repo.
Maybe you could .gitignore this folder but provide builds via github releases for users who want to use the theme without using a bundler / devserver.

**Comment by zuramai** [comment]
That's a nice idea! Yeah I think we should gitignore the dist folder, and for those who wants to directly use the template can download straight from github releases.

**Comment by Niksac** [comment]
I'll close this and create a new merge request

**Pull request closed without merging**
