### PR TITLE
fixed buttons id in form element checkbox page

### PR DESCRIPTION
**Pull request by alfianchii**

### CODE REVIEW

**Comment by fzn0x** [comment]
What is fixed here?  can you sent two screenshot that state the differences?

**Comment by fzn0x** [comment]
We may need to configure netlify soon @zuramai for easy preview

**Comment by alfianchii** [comment]
> What is fixed here? can you sent two screenshot that state the differences?

image

You can see at Colored and Glow checkbox text. If you click the checkbox text glow (e.g Secondary), then the Secondary checkbox in Colored Checkbox will be unchecked. I mean, the two attributes id both in Colored or Glow checkbox is same. So that's the problem.

**Review by fzn0x — APPROVED** [review]
Thanks

**Pull request merged**
